### ISSUE TITLE
Enable AI/ML in demo-app namespace

### ISSUE THREAD

**Issue by sstarzh** [f5devcentral/volt-demo-app#31]
AI/ML should be enabled for demo-app ( demo-app NS) to discover API endpoints and create OAS files. It also aids in malicious user detection

**Comment by kreynoldsf5** [comment]
Open Api Spec file download is covered with the App Type. I'll add a App Setting (new in the provider) to generate TSA.

We can evaluate malicious user detection from there.

@sstarzh

**Comment by kreynoldsf5** [comment]
Malicious user detection is populated.
